server:
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: task_admin
    password: p@ssw0rd
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  web:
    locale: ja
    locale-resolver: fixed
